---
title: "Bird Joins"
author: "Henry Oliver"
format: html
---

```{r}
library(here)
library(tidyverse)
library(lubridate)

```

```{r}
bird_observations <- as.data.frame (read_csv(here("data", "52_pp52_birds_1.csv")))

sites <- as.data.frame (read_csv(here("data", "52_pp52_sites_1.csv")))

surveys <- as.data.frame (read_csv(here("data", "52_pp52_surveys_1.csv")))

taxalists <- as.data.frame (read_csv(here("data", "52_pp52_taxalist_1.csv")))

```

```{r}
# Filter bird data to only incldue BHCO and RWBL species and LI-W and NU-C sites
birds_subset <- 
  bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL"), site_id %in% c("LI-W", "NU-C"))

# LEFT JOIN BY (site_id)
birds_subset <- birds_subset %>% 
  left_join(sites, by = "site_id") %>% 

# LEFT JOIN BY (species_id)
  left_join(taxalists, by = "species_id")


```


```{r}
birds_full <-
  full_join(birds_subset, sites, by = "site_id")
```



```{r}
bird_observations %>% 

rename(bird_obs_notes = notes)

birds <-
  bird_observations %>% 
  # join obs to species
  full_join(taxalists, by = "species_id") %>%
  # join both to sites
  full_join(sites, by = "site_id") %>% 
  # join all three to surveys
  full_join(surveys, by = "site_id") %>% 
  # select desired columns
  select(c(survey_date, common_name, park_name, bird_count))

birds <-
birds %>% 
  # make a new column with lubridate month function
  mutate(survey_month = month(survey_date)) %>% 
  # make new column a factor
  mutate(survey_month = factor(survey_month)) %>% 
  # move the new column
  relocate(survey_month, .after = survey_date) %>% 
  # group by park name and survey money
  group_by(park_name, survey_month) %>% 
  # show me sums of bird counts per group
  summarise(tot_bird_count = sum(bird_count)) %>% 
  # only show me these parks
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))

```

```{r}

```



